name: github publish action shell action
description: github publish action shell action
author: RekGRpth
runs:
  using: composite
  steps:
    - run: "${GITHUB_ACTION_PATH}/action.sh"
      shell: sh
